# thanks from stackoverflow answer:
# https://stackoverflow.com/questions/23793062/can-forks-be-synced-automatically-in-github

name: Merge upstream branches
on:
  schedule:
     # actually, ~5 minutes is the highest
     # effective frequency you will get
    - cron:  '0 0 * * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Rebase upstream
        run: |
          git config --global user.name 'sasakiyori'
          git config --global user.email 'sasakiyori33@gmail.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/golang/go.git
          git fetch upstream

          # If need sync all branches, need to get branch names and make a loop for sync
          # But I just need master branch to be synced temporarily
          # Neither forget the -b opt,
          # the feature/x ref is ambiguous at this stage

          # git checkout -b feature/x origin/feature/x
          # git merge --no-edit upstream/feature/x
          # git push origin feature/x

          git checkout master
          
          #git merge --no-edit upstream/master
          #git push origin master
          git rebase upstream/master
          git push origin master --force
          
